[project]
name = "small-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.25",
    "langchain-chroma>=0.2.3",
    "langchain-ollama>=0.3.2",
]
